---
- hosts: all
  connection: local

  vars_files:
    - meli.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../meli.config.yml
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
      ignore_errors: yes
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    - role: Comcast.sdkman
      sdkman_dir: ./sdkman
      sdkman_tmp_dir: /tmp
      sdkman_auto_answer: true
      sdkman_install_packages:
        - { candidate: gradle, version: '3.5' }
        - { candidate: maven, version: '3.5.4' }
        - { candidate: grails, version: '2.5.4' }
        - { candidate: grails, version: '2.5.3' }
        - { candidate: java, version: '8.0.191-oracle' }
      sdkman_defaults:
        gradle: '3.5'
        maven: '3.5.4'
        grails: '2.5.3'
        java: '8.0.191-oracle'
      sdkman_flush_caches_after:
        - archives
        - broadcast
        - candidates
        - temp

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
